version: '3'
services:
  grader:
    # image: docker
    build: ./runner
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3000:3000"
    tmpfs: /tmp

volumes:
  example: