version: '3'
services:
  api_gateway:
    build: ./api/gatewayService
    ports:
      - "8070:8080"

  browser:
    build: ./browser
    links:
      - api_gateway
    ports:
      - "8080:80"

  grader:
    build: ./grader
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3000:3000"